[General]
GeoLocale=system
SensitiveInfoMaskOn=true
ShowBiDirecSyncNoti=true
autoPlayGif=false
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
chatListPanelLastWidth=320
com.zoom.client.langid=0
com.zoom.pt.settings.closedcaption.fontsize=16
conf.webserver=https://zoom.us
currentMeetingId=
deviceID=04:D9:F5:82:40:9F
disableCef=false
disableUsePasskey=false
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCefGpu=false
enableCefLog=false
enableCefOsrMode=true
enableCefTa=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableUnifywebviewTa=false
enableWaylandShare=true
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
hideCrashReport=false
host.auto.grab.interval=10
isTransCoding=false
legacyAvatarCacheCleaned=1777915863
logLevel=info
newMeetingWithVideo=true
noSandbox=false
playSoundForNewMessage=false
shareBarTopMargin=0
shortcut_as_global_ShortcutID_Screenshot=false
shortcut_as_global_ShortcutID_ShowHideFloatingMeetingControls=true
showOneTimePTAICTipHubble=false
showOneTimeQueriesOptionTip=true
showOneTimeSmartRecognitionCoackMark=true
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
systemDockMargin=0
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=
webview.debug.enable=false
xwayland=false

[AS]
showframewindow=true
