[theme.templates.user.hyprland]
input_path  = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/hyprland.lua"
output_path = "~/.config/hypr/noctalia/noctalia-colors.lua"

[theme.templates.user.niri]
input_path  = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/niri.kdl"
output_path = "~/.config/niri/noctalia.kdl"

[theme.templates.user.reference]
input_path  = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/reference.toml"
output_path = "~/.config/noctalia/themes/reference.toml"

[theme.templates.user.bat]
input_path  = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/bat.tmTheme"
output_path = "~/.config/bat/themes/noctalia.tmTheme"
post_hook   = "bat cache --build"