[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/agr/.cache/noctalia/placeholder.json"

[templates.hyprland]
input_path = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/hyprland.conf"
output_path = "~/.config/hypr/noctalia/noctalia-colors.conf"

[templates.niri]
input_path = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/niri.kdl"
output_path = "~/.config/niri/noctalia.kdl"

[templates.sddm]
input_path = "/usr/share/sddm/themes/sddm-noctalia-theme/Assets/ColorScheme/Matugen/Matugen.qml.template"
output_path = "/usr/share/sddm/themes/sddm-noctalia-theme/Assets/ColorScheme/Noctalia-Shell/Noctalia-Shell.qml"

# [templates.bat]
# input_path = "~/devel/dotfiles/arch-noctalia/.config/noctalia/templates/bat.tmTheme"
# output_path = "~/.config/bat/themes/noctalia.tmTheme"
# post_hook = "bat cache --build"
