[preferred]
# Use Hyprland's own portal for screen sharing and shortcuts
default=hyprland;gtk;

# Specifically use GTK for the file picker since Hyprland doesn't have one
org.freedesktop.impl.portal.FileChooser=gtk
