$ht=Hyprtasking
$d=[$ht]

bindd = $mainMod,       A,          $d View All Workspaces,                 hyprtasking:toggle,         all
bindd = $mainMod ALT,   A,          $d View Workspaces On Cursor Monitor,   hyprtasking:toggle,         cursor
bindd = ,               ESCAPE,     $d Exit From Workspaces View,           hyprtasking:if_active,      hyprtasking:toggle cursor
bindd = $mainMod ALT,   X,          $d Kill Hovered Window,                 hyprtasking:if_active,      hyprtasking:killhovered

# bindd = $mainMod,       H,          $d Move Left On Hyprtasking View,       hyprtasking:if_active,  hyprtasking:move left
# bindd = $mainMod,       J,          $d Move Down On Hyprtasking View,       hyprtasking:if_active,  hyprtasking:move down
# bindd = $mainMod,       K,          $d Move Up On Hyprtasking View,         hyprtasking:if_active,  hyprtasking:move up
# bindd = $mainMod,       L,          $d Move Right On Hyprtasking View,      hyprtasking:if_active,  hyprtasking:move right

plugin {
    hyprtasking {
        layout = grid

        gap_size = 16
        bg_color = 0xff26233a
        border_size = 4
        exit_on_hovered = false
        warp_on_move_window = 1
        close_overview_on_reload = true

        drag_button = 0x110 # left mouse button
        select_button = 0x111 # right mouse button
        # for other mouse buttons see <linux/input-event-codes.h>

        gestures {
            enabled = true
            move_fingers = 3
            move_distance = 300
            open_fingers = 4
            open_distance = 300
            open_positive = true
        }

        grid {
            rows = 1
            cols = 4
            loop = false
            gaps_use_aspect_ratio = false
        }

        linear {
            top = true
            height = 300
            scroll_speed = 1.0
            blur = true
        }
    }
}

