# ── Input ─────────────────────────────────────────────────────────────────────
input {
    follow_mouse = 1
    kb_layout = us
    kb_variant = altgr-intl
    kb_options = fkeys:basic_13-24
    repeat_delay = 250
    repeat_rate = 40
    sensitivity = -0.4

    touchpad {
        natural_scroll = true
    }
}

cursor {
    hide_on_key_press = true
    no_hardware_cursors = true
}

exec-once = hyprctl setcursor Bibata-Rainbow-Modern 24
