# ── Environment ───────────────────────────────────────────────────────────────
# GPU device order — card1 preferred
env = WLR_DRM_DEVICES,/dev/dri/card1

exec-once = hyprpm reload -n      # Start Hyprland plugins
