# ── Environment ───────────────────────────────────────────────────────────────
env = TERMINAL,ghostty
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = hyprpm reload

exec-once = hyprctl --batch 'dispatch workspace 1; dispatch movecursortocorner 1'
