# ── Environment ───────────────────────────────────────────────────────────────
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = MOZ_ENABLE_WAYLAND,true
env = NIXOS_OZONE_WL,true
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
env = TERMINAL,ghostty
env = WLR_DRM_DEVICES,/dev/dri/card1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_MENU_PREFIX,arch-
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = hyprpm reload

exec-once = hyprctl --batch 'dispatch workspace 1; dispatch movecursortocorner 1'
