[config]

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'
