exec-once = vicinae server

unbind = ALT, SPACE

bindd = ALT, SPACE, Toggle Vicinae Launcher, exec, vicinae toggle #"Toggle Vicinae Launcher"

layerrule {
  name = vicinae_layer
  match:namespace = vicinae

  blur = on
  no_anim = on
  ignore_alpha = 0
}
