[General]
height=1364
width=1260
x=2560
y=0

[Browser]
autoPlayPreviews=true
dirConf=false
floatyUI=true
gridSize=4
lastSession=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\t\0\0\0\x2\0\0\0\b\0\0\0\x1\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0 \0\x66\0i\0l\0\x65\0:\0/\0/\0/\0h\0o\0m\0\x65\0/\0\x61\0g\0r\0\0\0\b\0\0\0\x1\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0\x10\0r\0\x65\0m\0o\0t\0\x65\0:\0/)
lastTabIndex=0
lastUsedTag=
listSize=0
overviewStart=false
previewFiles=false
previewerWindow=false
quickSidebarSection=true
restoreSession=true
showActionsBar=true
showHiddenFiles=true
showThumbnails=true
sideBarWidth=252
sidebarSections=13, 1, 3, 2
syncTerminal=true
terminalColorScheme=Maui-Dark
terminalFollowsColorScheme=true
viewType=0
windowTranslucency=true

[Sorting]
foldersFirst=true
group=false
sortBy=1
sortOrder=0
