$primary = rgb({{colors.primary.default.hex_stripped}})
$surface = rgb({{colors.surface.default.hex_stripped}})
$secondary = rgb({{colors.secondary.default.hex_stripped}})
$error = rgb({{colors.error.default.hex_stripped}})
$tertiary = rgb({{colors.tertiary.default.hex_stripped}})
$surface_variant = rgb({{colors.surface_variant.default.hex_stripped}})
$on_surface_variant = rgb({{colors.on_surface_variant.default.hex_stripped}})
$secondary_fixed_dim = rgb({{colors.secondary_fixed_dim.default.hex_stripped}})
$on_primary = rgb({{colors.on_primary.default.hex_stripped}})

general {
    col.active_border = $primary $secondary 45deg
    col.inactive_border = $on_surface_variant
}

group {
    col.border_active = $secondary $tertiary 45deg
    col.border_inactive = $on_surface_variant
    col.border_locked_active = $error $secondary_fixed_dim 45deg
    col.border_locked_inactive = $on_primary

    groupbar {
        col.active = $secondary $tertiary 45deg
        col.inactive = $on_surface_variant
        col.locked_active = $error $secondary_fixed_dim 45deg
        col.locked_inactive = $on_primary
    }
}
