# ~/.config/environment.d/wayland.conf

# Electron/Chromium
ELECTRON_OZONE_PLATFORM_HINT=auto
NIXOS_OZONE_WL=1

# Mozilla
MOZ_DBUS_REMOTE=1
MOZ_ENABLE_WAYLAND=1

# Qt
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt6ct
QT_QPA_PLATFORMTHEME_QT6=qt6ct
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# GTK
# GDK_BACKEND=wayland,x11

# SDL
SDL_VIDEODRIVER=wayland

# Clutter
CLUTTER_BACKEND=wayland

# Java
_JAVA_AWT_WM_NONREPARENTING=1
JAVA_TOOL_OPTIONS="-Dawt.useSystemAAFontSettings=on"

# XDG/Portal
XDG_MENU_PREFIX=arch-
XDG_SESSION_TYPE=wayland
