# Environment variables
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = MOZ_ENABLE_WAYLAND,true
env = NIXOS_OZONE_WL,true
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
env = TERMINAL,ghostty
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once =  qs -c noctalia-shell

# Idle pre lock hook
exec-once = $HOME/.local/bin/idle-pre-lock

# Idle inhibit on media playback
exec-once = $HOME/.local/bin/media-idle-inhibit
