$LOCK_CMD = hyde-shell lockscreen.sh # Calls $LOCKSCREEN default is hyprlock
$UNLOCK_CMD = sh -c 'sleep 3 && pkill -9 $(hyde-shell lockscreen --get)' # kills the lockscreen after 3 seconds for cleanup
$CHECK_IF_PLAYING_MEDIA = playerctl --all-players status 2>&1 | grep -q "Playing"

general {
    lock_cmd = $LOCK_CMD # command when `loginctl lock-session` is called
    unlock_cmd = $UNLOCK_CMD # command when `loginctl unlock-session` is called
    ignore_dbus_inhibit = false             # Ignore dbus idle-inhibit requests (false = respect them)
    ignore_systemd_inhibit = false          # Ignore systemd-inhibit --what=idle (false = respect them)
    # before_sleep_cmd =     # command ran before sleep
    # after_sleep_cmd = # notify-send "Awake!"  # command ran after sleep
}

# Dim display after 5 minutes
# listener {
#     timeout = 300
#     on-timeout = brightnessctl -s && brightnessctl s 1%
#     on-resume = brightnessctl -r
# }

# Lock after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# DPMS off after 11 minutes
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off # Turn off display
    on-resume = hyprctl dispatch dpms on   # Turn display back on
}

# Suspend after 15 minutes
listener {
    timeout = 900
    on-timeout = $CHECK_IF_PLAYING_MEDIA || systemctl suspend # Suspend system
}
