# Must always be the first import
# source = ./modules/root.conf

source = ./monitors.conf
source = ./workspaces.conf

source = ./modules/input.conf
source = ./modules/layers.conf
source = ./modules/windows.conf
source = ./modules/layout.conf
source = ./modules/misc.conf
source = ./modules/binds.conf
source = ./modules/animations.conf
source = ./modules/hyprtasking.conf
