[preferred]
# Use GNOME for screen sharing (screencast)
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome

# Use GTK for most other standard UI elements
default=gtk;gnome;
